services:
  nginx:
    container_name: ${PROJECT_NAME}-nginx
    build:
      context: ..
      dockerfile: localdocker/nginx.Dockerfile
    env_file:
      - .env
    user: nginx
    volumes:
      - ../api/storage/:/var/www/storage/:z
    ports:
      - "8000:8000"
    depends_on:
      - api
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    container_name: ${PROJECT_NAME}-api
    build:
      context: ..
      dockerfile: localdocker/api.Dockerfile
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
    user: "1000:1000"
    volumes:
      - ../api/:/var/www:z
    networks:
      - backend

  app:
    container_name: ${PROJECT_NAME}-app
    build:
      context: ..
      dockerfile: localdocker/app.Dockerfile
    depends_on:
      api:
        condition: service_started
      nginx:
        condition: service_healthy
    env_file:
      - .env
    user: "1000:1000"
    volumes:
      - ../app/:/app:z
    ports:
      - "5173:5173"
    networks:
      - backend

  mariadb:
    container_name: ${PROJECT_NAME}-mariadb
    image: mariadb:latest
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

  postgres:
    container_name: ${PROJECT_NAME}-postgres
    image: postgres:17
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-dav.sh:/docker-entrypoint-initdb.d/init-dav.sh
    networks:
      - backend

  redis:
    container_name: ${PROJECT_NAME}-redis
    image: redis:latest
    env_file:
      - .env
    volumes:
      - redis_data:/data
    networks:
      - backend

volumes:
  mariadb_data:
  redis_data:
  pg_data:

networks:
  backend:
    driver: bridge
